% This script demonstrates using the matrix form of L for TFI inversion.
% With this form of L, the processing is typically limited to surface models
% with around 6000 faces and voxel sizes of approximately 2-2.5 mm on a personal PC.
% While this approach is not practical for real applications, it is simple
% and helpful for users to understand the project.
%
%   Created by Haodong Zhong on 2024.11.25
%   Last modified by Haodong Zhong on 2024.11.25

%% GRE Data Preprocessing Example
% The basic variable names related to QSM follow the conventions of the MEDI_toolbox.
iMag = sqrt(sum(abs(iField).^2,4));
Mask = BET(iMag, matrix_size, voxel_size);
[iFreq_raw, N_std] = Fit_ppm_complex_TE(iField, TE);
iFreq = unwrapPhase(iMag, iFreq_raw, matrix_size);

%% Generate the Mesh
% If the mesh generated by this code does not meet your requirements,
% you can replace it with a custom-generated mesh and the corresponding mask inside the mesh.
% The mesh should ideally have fewer than 6000 faces.
% If some regions of the mesh are too dense, 
% you can manually adjust the Mask to improve the mesh quality.

Mask(:,:,2)=0;
[mesh, mask] = generateMeshAndMask(3.5, Mask, voxel_size, 1);
plotModel(mesh);

%% Calculate L
gq_number = 64;
[L, mask] = L_simple(mesh, gq_number, voxel_size, mask);
ftest = L*ones([size(mesh.elt,1) ,1]);

%% Example of QSM inversion using the matrix form of L
% , simplified by omitting the preconditioner and CSF regularization
params_gTFI_MatrixForm = [];
params_gTFI_MatrixForm.delta_TE = delta_TE;
params_gTFI_MatrixForm.CF = CF;
params_gTFI_MatrixForm.voxel_size = voxel_size;
params_gTFI_MatrixForm.mask = mask;
params_gTFI_MatrixForm.iMag = iMag;
params_gTFI_MatrixForm.mesh = mesh;
params_gTFI_MatrixForm.f = iFreq;
params_gTFI_MatrixForm.N_std = N_std;
params_gTFI_MatrixForm.B0_dir = B0_dir;
params_gTFI_MatrixForm.lambda = 1000;
params_gTFI_MatrixForm.L = L;

gTFI = gTFI_matrixForm(params_gTFI_MatrixForm);

